Repository CSUCI-Adv-SE/Summi, pull requests merged in 2023-02, with the labels that each got.

#3 added github actions for every branches
  .github/workflows/django.yml
Labels: documentation

#4 Upload api feature
  .gitignore
  Dockerfile
  requirements.txt
  summI/settings.py
  summI/urls.py
  summIApp/__init__.py
  summIApp/admin.py
  summIApp/apps.py
  summIApp/constants.py
  summIApp/migrations/__init__.py
  summIApp/models.py
  summIApp/tests.py
  summIApp/urls.py
  summIApp/utils.py
  summIApp/utils_validations.py
  summIApp/views.py
Labels: enhancement

#19 Get file api
  .gitignore
  requirements.txt
  summI/settings.py
  summI/urls.py
  summIApp/models.py
  summIApp/urls.py
  summIApp/views.py
Labels: enhancement

#20 Text recognition
  .gitignore
  requirements.txt
  summIApp/ocr_model/summi_ocr.py
  summIApp/urls.py
  summIApp/views.py
Labels: enhancement

#16 Upload api feature
  summIApp/migrations/0001_initial.py
  summIApp/migrations/0002_useruploadedfiles_is this file public.py
  summIApp/migrations/0003_remove_useruploadedfiles_is this file public_and_more.py
Labels: bug
